@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "ROOT=%~dp0..\..\"
cd /d "%ROOT%"

if exist Cargo.lock exit /B 0

echo.
echo ==^> Bootstrap Cargo.lock with pinned Cargo 1.98.0
where cargo >nul 2>&1
if errorlevel 1 (
  echo cargo was not found on PATH.
  exit /B 1
)

for /f "delims=" %%V in ('cargo --version') do set "CARGO_VERSION=%%V"
echo !CARGO_VERSION!
echo !CARGO_VERSION! | findstr /B /C:"cargo 1.98.0 " >nul
if errorlevel 1 (
  echo Cargo.lock bootstrap requires cargo 1.98.0 exactly. Active cargo: !CARGO_VERSION!
  exit /B 1
)

cargo generate-lockfile
if errorlevel 1 (
  echo Cargo 1.98.0 failed to generate Cargo.lock from the repository manifests.
  if exist Cargo.lock del /Q Cargo.lock >nul 2>&1
  exit /B 1
)

cargo metadata --locked --format-version 1 >nul
if errorlevel 1 (
  echo The generated Cargo.lock failed immediate --locked verification. Removing it.
  del /Q Cargo.lock >nul 2>&1
  exit /B 1
)

echo Cargo.lock generated by Cargo 1.98.0 and verified with cargo metadata --locked.
exit /B 0
