#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

[[ -f Cargo.lock ]] && exit 0

echo
echo "==> Bootstrap Cargo.lock with pinned Cargo 1.98.0"
command -v cargo >/dev/null 2>&1 || {
  echo "cargo was not found on PATH." >&2
  exit 1
}
CARGO_VERSION="$(cargo --version)"
echo "$CARGO_VERSION"
if [[ "$CARGO_VERSION" != cargo\ 1.98.0\ * ]]; then
  echo "Cargo.lock bootstrap requires cargo 1.98.0 exactly. Active cargo: $CARGO_VERSION" >&2
  exit 1
fi

if ! cargo generate-lockfile; then
  echo "Cargo 1.98.0 failed to generate Cargo.lock from the repository manifests." >&2
  rm -f Cargo.lock
  exit 1
fi
if ! cargo metadata --locked --format-version 1 >/dev/null; then
  echo "The generated Cargo.lock failed immediate --locked verification. Removing it." >&2
  rm -f Cargo.lock
  exit 1
fi

echo "Cargo.lock generated by Cargo 1.98.0 and verified with cargo metadata --locked."
